### ISSUE TITLE
(Sqlite) Why is it that you create a new record for each item from the same player?

### ISSUE THREAD

**Issue by rjworks** [Shock95x/AuctionHouse#42]
Why is it that you create a new record for each item from the same player? Why not have one record for one player  and have an items column where all items on auction by the same player is stored?

**Comment by Shock95x** [comment]
It's something that I thought about before but I just went with how it is right now since it's more convenient and manageable. For one I wouldn't have to serialize and unserialize every listing including the item NBT which would be inefficient and would likely result in more time to save and load listings. SQL can also handle millions of records so I don't really see it as an issue.
